-- TODO All should be CREATE IF NOT EXISTS or similar...
PRAGMA foreign_keys = true;
CREATE TABLE users (
    id INTEGER PRIMARY KEY ASC UNIQUE,
    nick TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    registered_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    id INTEGER PRIMARY KEY ASC,
    host_id INTEGER,
    name TEXT NOT NULL,
    password TEXT,
    created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_private INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (host_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE rel_users_rooms (
    user_id INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE formulas (
    id INTEGER PRIMARY KEY ASC,
    formula TEXT NOT NULL
);

CREATE TABLE results (
    id INTEGER PRIMARY KEY ASC,
    user_id INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    formula_id INTEGER NOT NULL,
    result_time INTEGER NOT NULL,
    result_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY(formula_id) REFERENCES formulas(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE chat (
    id INTEGER PRIMARY KEY ASC,
    user_id INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    message INTEGER NOT NULL,
    post_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);